config/routes.rb
ActionController::Routing::Routes.draw do |map|
  

  map.home '', :controller => "projects", :action => 'dashboard'

  map.connect ':controller/service.wsdl', :action => 'wsdl'
  
  map.resources :hosts
  map.resources :recipes, :collection => {:preview => :get}
  map.resources :projects, :member => {:dashboard => :get} do |projects|
    projects.resources :project_users

    projects.resources :project_configurations
    
    projects.resources :stages, :member => {:capfile => :get, :recipes => :any, :tasks => :get} do |stages|
      stages.resources :stage_configurations
      stages.resources :roles
      stages.resources :deployments, :collection => {:latest => :get}, :member => {:cancel => :post}
    end
  end
  
  map.resources :users,:member => {:deployments => :get, :enable => :post}
  map.resources :sessions, :collection => {:version => :get}
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.login  '/login', :controller => 'sessions', :action => 'new'
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  
  map.stylesheet '/stylesheets/application.css', :controller => 'stylesheets', :action => 'application'

  map.connect ':controller/:action/:id.:format'
  map.connect ':controller/:action/:id'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users

  has_many :stages, :dependent => :destroy, :order => 'name ASC'
  has_many :deployments, :through => :stages
  has_many :configuration_parameters, :dependent => :destroy, :class_name => "ProjectConfiguration", :order => 'name ASC'
  
  validates_uniqueness_of :name
  validates_presence_of :name
  validates_length_of :name, :maximum => 250
  validates_inclusion_of :template, :in => ProjectConfiguration.templates.keys
  
  after_create :create_template_defaults, :add_default_stage
  
  attr_accessible :name, :description, :template, :project_config
  
  # creates the default configuration parameters based on the template
  def create_template_defaults
    unless template.blank?
      
      ProjectConfiguration.templates[template]::CONFIG.each do |k, v|
        config = self.configuration_parameters.build(:name => k.to_s, :value => v.to_s)
        if self.project_config.has_key?(k.to_s)
          config = self.configuration_parameters.build(:name => k.to_s, :value => self.project_config[k.to_s])
        end

        if k.to_sym == :application          
          config.value = self.name.gsub(/[^0-9a-zA-Z]/,"_").underscore
        end  
        config.save!
      end
    end
  end
  
  # add default stage to this project 
  def add_default_stage
    stage_name = "Test"
    if self.project_config.has_key?("stage_name")
      stage_name = self.project_config["stage_name"]
    end
    @stage = self.stages.build({:name => stage_name})
    self.add_default_recipe
    @stage.save!
    self.add_default_host
  end
  
  def add_default_recipe
    if self.project_config.has_key?("stage_recipe_ids")
      @stage.recipe_ids = self.project_config["stage_recipe_ids"].split(",").map(&:strip)
    else
      @stage.recipe_ids = ["13"]
    end
  end
  
  def add_default_host
    if self.project_config.has_key?("role_host_id")
      role_name = "app"
      if self.project_config.has_key?("role_name")
        role_name = self.project_config["role_name"]
      end
      role = @stage.roles.build({:host_id => self.project_config["role_host_id"], :name => role_name})
      role.save!
    end
  end
  
  # returns a string with all custom tasks to be loaded by the Capistrano config
  def tasks
    ProjectConfiguration.templates[template]::TASKS
  end
  
  # returns a better form of the project name for use inside Capistrano recipes
  def webistrano_project_name
    self.name.underscore.gsub(/[^a-zA-Z0-9\-\_]/, '_')
  end
  
  def recent_deployments(limit=3)
    self.deployments.find(:all, :limit => limit, :order => 'deployments.created_at DESC')
  end
  
  def prepare_cloning(other)
    self.name = "Clone of #{other.name}"
    self.description = "Clone of #{other.name}: #{other.description}"
    self.template = other.template
  end
  
  def clone(other)  
    self.stages.destroy_all
    self.configuration_parameters.destroy_all
      
    other.configuration_parameters.each do |conf|
      self.configuration_parameters << ProjectConfiguration.new(:name => conf.name, :value => conf.value, :prompt_on_deploy => conf.prompt_on_deploy)
    end
    
    other.stages.each do |stage|
      new_stage = Stage.new
      new_stage.project = self
      new_stage.name = stage.name
      new_stage.alert_emails = stage.alert_emails
      new_stage.save!
      
      stage.configuration_parameters.each do |conf|
        new_stage.configuration_parameters << StageConfiguration.new(:name => conf.name, :value => conf.value, :prompt_on_deploy => conf.prompt_on_deploy)
      end
      
      stage.recipes.each do |recipe|
        new_stage.recipes << recipe
      end

      stage.roles.each do |role|
        new_stage.roles << Role.new(role.attributes)
      end
    end
    
    self.reload
  end
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :load_templates, :only => [:new, :create, :edit, :update]
  before_filter :ensure_admin, :only => [:new, :edit, :destroy, :create, :update]
  
  # GET /projects/dashboard
  def dashboard
    @deployments = Deployment.find(:all, :limit => 3, :order => 'created_at DESC')

    respond_to do |format|
      format.html # dashboard.rhtml
    end
  end
  
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.find(:all, :order => 'name ASC')

    respond_to do |format|
      format.html # index.rhtml
      format.xml  { render :xml => @projects.to_xml }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.rhtml
      format.xml  { render :xml => @project.to_xml }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
    if load_clone_original
      @project.prepare_cloning(@original)
      render :action => 'clone' and return
    end
  end

  # GET /projects/1;edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    
    configurations = params[:configurations][:values]
    project_config = Hash.new
    unless configurations.empty?
      lines = configurations.split("\n")
      lines.each { |line| 
          parts = line.split("=")
          if parts.length >= 2
            project_config[parts[0].strip] = parts[1].strip 
          end
      }
    end
    @project.write_attribute(:project_config, project_config)
    
    if load_clone_original
      action_to_render = 'clone'  
    else
      action_to_render = 'new'  
    end
      
    respond_to do |format|
      if @project.save
        
        @project.clone(@original) if load_clone_original
        
        flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to project_url(@project) }
        format.xml  { head :created, :location => project_url(@project) }
      else
        format.html { render :action => action_to_render }
        format.xml  { render :xml => @project.errors.to_xml }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to project_url(@project) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors.to_xml }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      flash[:notice] = 'Project was successfully deleted.'
      format.html { redirect_to projects_url }
      format.xml  { head :ok }
    end
  end
  
  protected
  def load_templates
    @templates = ProjectConfiguration.templates.sort.collect do |k,v|
      [k.to_s.titleize, k.to_s]
    end  
    
    @template_infos = ProjectConfiguration.templates.collect do |k,v|
      [k.to_s, v::DESC]
    end
  end
  
  def load_clone_original
    if params[:clone]
      @original = Project.find(params[:clone])
    else
      false
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def clone_form_path(project)
    "#{new_project_path}?clone=#{project.id}"
  end
  
  def clone_path(project)
    "#{projects_path}?clone=#{project.id}"
  end
  
end

app/views/projects/_configs.html.erb
<% if @project.configuration_parameters.empty? %>
  <br/>
    <strong>No project wide configuration added yet.</strong><br/>
     Project configuration is overridden by stage configurations. 
  </p>
<% else %>
  <table class="sortable">
    <tr>
      <th width="1%">Name</th>
      <th width="98%">Value</th>
      <th width="1%">Prompt?</th>
    </tr>
  <% for config in @project.configuration_parameters %>
    <tr class="<%= cycle :even, :odd, :name => 'configs' %>">
      <td title="<%=h config.name %>"><%= truncate(h(config.name), :length => 25) %></td>
      <td title="<%=h config.value %>"><%=h truncate(hide_password_in_value(config), :length => 45) %></td>
      <td><%= config.prompt_status_in_html %></td>
      <td><%= link_to 'Edit', edit_project_project_configuration_path(@project, config) %></td>
      <td><%= link_to 'Delete', project_project_configuration_path(@project, config), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/projects/_deployments.html.erb
<% if @project.deployments.empty? %>
  <br/>
    This project was never deployed. 
  <br/>
<% else %>
<% @project.recent_deployments.each do |deployment| %>
    <%= render(:partial => 'deployments/list_item', :locals => {:deployment => deployment}) %>
  <% end %>
<% end %>
<br />

app/views/projects/_form.html.erb
<% flashed_errors(:project) %>
<p>
  <b>Name</b><br />
  <%= text_field 'project', 'name', :style =>'width:330px;' %>
</p>
<p>
  <b>Project Type</b><br />
  <%= select('project', 'template', @templates, { :include_blank => false, :selected => "magento_quick" }) %>
</p>
<p>
  <b>Description</b><br />
  <%= text_area 'project', 'description', :style =>'width:330px; height: 100px' %>
</p>

<p>
  <b>Configurations</b><br />
  <%= text_area 'configurations', 'values', :style =>'width:330px; height: 100px' %>
</p>


<% content_for(:page_scripts) do %>
 <script type="text/javascript">
 
    Event.observe(window, 'load', function(){
      Event.observe('project_template', 'change', show_template_info);
      
      // show info for already chosen template
      show_template_info();
    });
 
   function show_template_info(){
     hide_all_infos();
     var info_to_show = $F('project_template') + '_desc';
     $(info_to_show).show();
   }
   
   function hide_all_infos(){
     <% for template in @template_infos %>
       $('<%=h template.first %>_desc').hide();
     <% end %>
   }

 </script>
<% end %>
<% content_for(:action_box) do %>
<div class="small_box">
  <div class="small_box_top"></div>
  <div class="small_box_middle" style="min-height: 230px; *height: 230px;">
		 <h3>Project Type:</h3>
		   <% for template in @template_infos %>
		     <div id="<%=h template.first %>_desc" style="display:none;">
		         <b><%= template.first.to_s.titleize %>:</b><br />
		         <%= template.last %>
		     </div>
		   <% end %>
  </div>
  <div class="small_box_bottom"></div>
</div>
<% end %>

app/views/projects/_stages.html.erb
<% if @project.stages.empty? %>
<br/>
    <strong>No stages configured yet.</strong><br/> Stages represent one deployment scenario of a project. Typical stages are a 'Prod', 'Test' and 'Dev' stage.
<br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="34%">Name</th>
      <th width="33%">#Hosts</th>
      <th width="33%">#Deployments</th>
    </tr>
  <% for stage in @project.stages %>
    <tr class="<%= cycle :even, :odd, :name => 'stages' %>">
      <td><%= link_to h(stage.name), project_stage_path(@project, stage) %></td>
      <td><%=h stage.hosts.count  %></td>
      <td><%=h stage.deployments.count  %></td>
      <td><%= link_to 'Edit', edit_project_stage_path(@project, stage) %></td>
      <td><%= link_to 'Delete', project_stage_path(@project, stage), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/projects/_users.html.erb
<% if @project.users.empty? %>
  <br/>
    No users added yet.<br />
  <br/>
<% else %>
  <table class="sortable">
    <% for user in @project.users %>
      <tr class="<%= cycle :even, :odd, :name => 'users'  %>">
        <td nowrap><%= link_to h(user.login), user_path(user) %></td>
        <% if current_user.admin? -%>
          <td><%= link_to 'Remove', project_project_user_path(@project, user), :confirm => 'Are you sure?', :method => :delete %></td>
        <% end -%>
      </tr>
    <% end %>
  </table>
<% end %>

<% if current_user.admin? %>
<form action='<%=project_project_users_path(@project)%>' method='post'>
	<label>Add user: </label>
	<%=select 'project_user', 'id', User.find(:all).reject{|u| @project.user_ids.include?(u.id)}.collect{|u| [u.login, u.id]}%>
	<input type='submit' value='Add' />
</form>
<%end%>

app/views/projects/clone.html.erb
<% form_for(:project, :url => clone_path(@original)) do |f| %>

  <%= render(:partial => 'form')%>
  
  <%= link_to 'Back to projects', projects_path, :class => 'arrow_link ontheright', :style => 'margin-right: 80px' %>

  <p>
    <%= submit_tag "Clone" %>
  </p>
<% end %>

<% content_for(:breadcrumb) do %>
  <% breadcrumb_box do %>
    <%= link_to "Back to project", project_path(@original), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Clone <%= link_to @original.name, project_path(@original) %> 
  <% end %>
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Clone project #{h(@original.name)}" %>
  <h2>Clone project</h2>
<% end %>

app/views/projects/dashboard.html.erb
<fieldset class="fieldset">
  <legend>Introduction and help</legend>
  <div style="float: right; padding: 10px 5px 5px 5px;">
    <a href="http://labs.peritor.com/webistrano" target="_blank"><%= image_tag('peritor_theme/webistrano_screenshot.png', :border => '0', :width => '200', :height => '151')%></a>
  </div>
  <div style="padding-top: 5px;">
   Welcome to Webistrano. Your first steps should be to create a project with a stage.
   This stage can then be deployed once you made at least one host known to Webistrano.
   <br /><br />
   For help and more documentation, see
   <br />
   <ul>
     <li><a href="http://labs.peritor.com/webistrano/">Wiki</a></li>
     <li><a href="http://labs.peritor.com/webistrano/wiki/ConfigurationParameter">Configuration Parameter</a></li>
     <li><a href="http://labs.peritor.com/webistrano/wiki/FAQ">FAQ</a></li>
   </ul>
   <br />
   Webistrano is Open Source. Paid support is available by <a href="http://www.peritor.com">Peritor Consulting</a>.
  </div>
</fieldset>

<br />

<fieldset class="fieldset">
  <legend>Recent deployments</legend>
  <% if @deployments.empty? %>
    <br/>
      No recent deployments.
    <br/>
  <% else %>
    <% @deployments.each do |deployment| %>
      <%= render(:partial => 'deployments/list_item', :locals => {:deployment => deployment}) %>
    <% end %>
  <% end %>
</fieldset>

<br />

<% content_for(:page_title) do %>
  <% @page_title = "Welcome to Webistrano" %>
  <h2>Welcome to Webistrano</h2>
<% end %>

app/views/projects/edit.html.erb
<% form_for(:project, :url => project_path(@project), :html => { :method => :put }) do |f| %>
  
  <%= render(:partial => 'form')%>

  <%= link_to 'Back to project', project_path(@project), :class => 'arrow_link ontheright', :style => 'margin-right: 80px' %>

  <p>
    <%= submit_tag "Update project" %>
  </p>

<% end %>

<% content_for(:breadcrumb) do %>
  <% breadcrumb_box do %>
    <%= link_to "Back to project", project_path(current_project), :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    Project <%= link_to current_project.name, project_path(current_project) %> &gt; 
    Edit
  <% end %>
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "Edit project #{h(current_project.name)}" %>
  <h2>Edit <%= link_to h(current_project.name), project_path(current_project) %></h2>
<% end %>

app/views/projects/index.html.erb
<%projects = current_user.admin? ? Project.find(:all) : current_user.projects%>
<h2>Projects</h2>

<fieldset class="fieldset">
  <legend> <%=h pluralize(projects.length, 'Project')%> listed for you</legend>

<% if projects.empty? %>
<br/>
    No projects listed for you.<br />
  <br/>
<% else %>
  <table class="sortable">
    <tr>
      <th width="1%">Name</th>
      <th width="96%">Description</th>
      <th width="1%">#Stages</th>
      <th width="1%">#Deploy.</th>
      <th width="1%">Created At</th>
    </tr>
    <% for project in projects %>
      <tr class="<%= cycle :even, :odd, :name => 'projects'  %>">
        <td><%= link_to h(project.name), project_path(project) %></td>
        <td><%=h project.description %></td>
        <td><%=h project.stages.count %></td>
        <td><%=h project.deployments.count %></td>
        <td><%=h project.created_at.to_s(:date_with_day) %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
		<%if current_user.admin?%>
        <td><%= link_to 'Delete', project_path(project), :confirm => 'Are you sure?', :method => :delete %></td>
		<%end%>
      </tr>
    <% end %>
  </table>
<% end %>

<br />

<%if current_user.admin?%>
<%= link_to 'New project', new_project_path, :class => 'arrow_link' %>
<%end%>

</fieldset>

app/views/projects/new.html.erb
<% form_for(:project, :url => projects_path) do |f| %>
<div style="width:335px;">

  <%= render(:partial => 'form')%>
  
  <%= link_to 'Back to projects', projects_path, :class => 'arrow_link ontheright' %>

  <p>
    <%= submit_tag "Create" %>
  </p>
</div>
<% end %>


<% content_for(:breadcrumb) do %>
  <% breadcrumb_box do %>
    <%= link_to "Manage Projects", projects_path, :style => "float:right", :class => "arrow_link" %>
    <%= link_to "Projects", projects_path %> &gt; 
    New
  <% end %>
<% end %>

<% content_for(:page_title) do %>
  <% @page_title = "New project" %>
  <h2>New project</h2>
<% end %>

app/views/projects/show.html.erb
<h2>Project: <%=h @project.name %></h2>

<div class="special_box stages_box">
  <% if @project.stages.count > 0 %>
    <p><strong>Choose a stage:</strong></p>
    <% for stage in @project.stages %>
        <p><%= link_to h(stage.name), project_stage_path(@project, stage), :class => 'arrow_link'  %></p>
    <% end %>
  <% else %>  
    <p><strong>No stage configured yet</strong></p>
    <%= link_to 'New stage', new_project_stage_path(@project), :class => 'arrow_link' %>
  <% end %>
</div>

<div style="float: left; width:380px;">
  <div class="box_top_left">
    <div class="box_top_right">
      <div class="box_top">
    </div>
    </div>
  </div>
  <div class="box_body" style="min-height: 123px;">
    <div>
    <p>
    <b>Description:</b>
      <%=h @project.description %>
    </p>
    <p>
      <b>Project Type:</b>
      <%=h @project.template %>
    </p>
    <p>
      <b>#Deployments:</b>
      <%=h @project.deployments.count %>
    </p><br />
    <% if current_user.admin? %>
    <%= link_to 'Edit Project', edit_project_path(@project), :class => 'arrow_link' %> | 
    <%= link_to 'Delete', project_path(@project), :confirm => 'Are you sure?', :method => :delete, :class => 'arrow_link' %>
    <%end%>
  </div>  
  </div>
  <div class="box_bottom_left">
    <div class="box_bottom_right">
      <div class="box_bottom">  
      </div>
    </div>
  </div>
</div>

<div class="clear"></div>
<br>
<% if current_user.admin? %>
<fieldset class="fieldset">
  <legend>Project configuration</legend>
  <%= render(:partial => 'configs')%>
  <br />
  <%= link_to 'New configuration', new_project_project_configuration_path(@project), :class => 'arrow_link' %>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Stages</legend>
  <%= render(:partial => 'stages')%>
  <br />
  <%= link_to 'New stage', new_project_stage_path(@project), :class => 'arrow_link' %>
</fieldset>

<br /><br />

<fieldset class="fieldset">
  <legend>Privileged users</legend>
  <%= render(:partial => 'users')%>
  <br />
</fieldset>
<%end%>